# Generated by Django 6.0.4 on 2026-04-21 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0003_anamnesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('audiometria', 'Audiometría'), ('impedanciometria', 'Impedanciometría'), ('otoscopia', 'Otoscopía'), ('otro', 'Otro')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evaluaciones/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='Login.paciente')),
            ],
        ),
    ]
