# Generated by Django 6.0.4 on 2026-04-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(default='tonal', max_length=20)),
                ('audiograma', models.JSONField(blank=True, default=list)),
                ('sds_od', models.IntegerField(blank=True, null=True)),
                ('sds_oi', models.IntegerField(blank=True, null=True)),
                ('int_od', models.IntegerField(blank=True, null=True)),
                ('int_oi', models.IntegerField(blank=True, null=True)),
                ('mkg_od', models.IntegerField(blank=True, null=True)),
                ('mkg_oi', models.IntegerField(blank=True, null=True)),
                ('ptp_va_od', models.IntegerField(blank=True, null=True)),
                ('ptp_vo_od', models.IntegerField(blank=True, null=True)),
                ('ptp_va_oi', models.IntegerField(blank=True, null=True)),
                ('ptp_vo_oi', models.IntegerField(blank=True, null=True)),
                ('weber_250', models.CharField(blank=True, max_length=10)),
                ('weber_500', models.CharField(blank=True, max_length=10)),
                ('weber_1000', models.CharField(blank=True, max_length=10)),
                ('rinne_512_od', models.CharField(blank=True, max_length=5)),
                ('rinne_512_oi', models.CharField(blank=True, max_length=5)),
                ('deterioro_test', models.CharField(blank=True, max_length=20)),
                ('det_500_od', models.IntegerField(blank=True, null=True)),
                ('det_1000_od', models.IntegerField(blank=True, null=True)),
                ('det_2000_od', models.IntegerField(blank=True, null=True)),
                ('det_4000_od', models.IntegerField(blank=True, null=True)),
                ('det_500_oi', models.IntegerField(blank=True, null=True)),
                ('det_1000_oi', models.IntegerField(blank=True, null=True)),
                ('det_2000_oi', models.IntegerField(blank=True, null=True)),
                ('det_4000_oi', models.IntegerField(blank=True, null=True)),
                ('tin_presente', models.BooleanField(default=False)),
                ('tin_ausente', models.BooleanField(default=False)),
                ('tin_ocasional', models.BooleanField(default=False)),
                ('tin_examen_positivo', models.BooleanField(default=False)),
                ('tin_od', models.BooleanField(default=False)),
                ('tin_oi', models.BooleanField(default=False)),
                ('tin_bilateral', models.BooleanField(default=False)),
                ('tin_tono_puro', models.BooleanField(default=False)),
                ('tin_ruido_blanco', models.BooleanField(default=False)),
                ('tin_ruido_banda', models.BooleanField(default=False)),
                ('tin_continuo', models.BooleanField(default=False)),
                ('tin_pulsatil', models.BooleanField(default=False)),
                ('tin_fluctuante', models.BooleanField(default=False)),
                ('tin_db_hl', models.IntegerField(blank=True, null=True)),
                ('tin_db_sl', models.IntegerField(blank=True, null=True)),
                ('tin_freq', models.IntegerField(blank=True, null=True)),
                ('tin_masking', models.IntegerField(blank=True, null=True)),
                ('tin_inh_od', models.BooleanField(default=False)),
                ('tin_inh_oi', models.BooleanField(default=False)),
                ('tin_inh_bi', models.BooleanField(default=False)),
                ('tin_inh_tc', models.BooleanField(default=False)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiometria', to='evaluaciones.evaluacion')),
            ],
        ),
    ]
