# Generated by Django 6.0.4 on 2026-08-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_audiometria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cae_od', models.CharField(blank=True, max_length=255)),
                ('membrana_od', models.CharField(blank=True, max_length=255)),
                ('cae_oi', models.CharField(blank=True, max_length=255)),
                ('membrana_oi', models.CharField(blank=True, max_length=255)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otoscopia', to='evaluaciones.evaluacion')),
            ],
        ),
    ]
