# Generated by Django 6.0.4 on 2026-08-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_otoscopia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impedanciometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_od', models.IntegerField(blank=True, null=True)),
                ('compliancia_od', models.FloatField(blank=True, null=True)),
                ('volumen_od', models.FloatField(blank=True, null=True)),
                ('curva_od', models.CharField(blank=True, choices=[('A', 'Tipo A'), ('As', 'Tipo As'), ('Ad', 'Tipo Ad'), ('B', 'Tipo B'), ('C', 'Tipo C')], max_length=5)),
                ('presion_oi', models.IntegerField(blank=True, null=True)),
                ('compliancia_oi', models.FloatField(blank=True, null=True)),
                ('volumen_oi', models.FloatField(blank=True, null=True)),
                ('curva_oi', models.CharField(blank=True, choices=[('A', 'Tipo A'), ('As', 'Tipo As'), ('Ad', 'Tipo Ad'), ('B', 'Tipo B'), ('C', 'Tipo C')], max_length=5)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impedanciometria', to='evaluaciones.evaluacion')),
            ],
        ),
    ]
