# Generated by Django 6.0.4 on 2026-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(choices=[('fonasa', 'Fonasa'), ('isapre', 'Isapre'), ('capredena', 'Capredena'), ('dipreca', 'Dipreca')], default='fonasa', max_length=20),
        ),
    ]
