# Generated by Django 6.0.4 on 2026-04-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_paciente_email_paciente_prevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('antecedentes_auditivos', models.TextField(blank=True, null=True)),
                ('hipoacusia', models.BooleanField(default=False)),
                ('tinnitus', models.BooleanField(default=False)),
                ('vertigo', models.BooleanField(default=False)),
                ('otalgia', models.BooleanField(default=False)),
                ('exposicion_ruido', models.BooleanField(default=False)),
                ('uso_audifonos', models.BooleanField(default=False)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='Login.paciente')),
            ],
        ),
    ]
